print('Hello Welcome to Basic Python Calculator') 
name = input('What is your name?')
print(f'Hello {name}! Welcome to Basic Python Calculator')
print('Please select the operation you want to perform')
print('1. Addition')
print('2. Subtraction')
print('3. Multiplication')
print('4. Division')
print('5. Modulus')
print('6. Exponent')
print('7. Floor Division')
print('8. Exit')
