print('Hello Welcome to Basic Python Calculator') 
name = input('What is your name?')
print(f'Hello {name}! Welcome to Basic Python Calculator')
print('Please select the operation you want to perform')
print('1. Addition')
print('2. Subtraction')
print('3. Multiplication')
print('4. Division')
print('5. Modulus')
print('6. Exponent')
print('7. Floor Division')
print('8. Exit')
operation = input('Enter your choice (1/2/3/4/5/6/7/8):')
if operation == '1':
    print('You have selected Addition')
    num1 = int(input('Enter first number:'))
    num2 = int(input('Enter second number:'))
    print(f'Addition of {num1} and {num2} is {num1 + num2}')
elif operation == '2':
    print('You have selected Subtraction')
    num1 = int(input('Enter first number:'))
    num2 = int(input('Enter second number:'))
    print(f'Subtraction of {num1} and {num2} is {num1 - num2}')
elif operation == '3':
    print('You have selected Multiplication')
    num1 = int(input('Enter first number:'))
    num2 = int(input('Enter second number:'))
    print(f'Multiplication of {num1} and {num2} is {num1 * num2}')
elif operation == '4':
    print('You have selected Division')
    num1 = int(input('Enter first number:'))
    num2 = int(input('Enter second number:'))
    print(f'Division of {num1} and {num2} is {num1 / num2}')
elif operation == '5':
    print('You have selected Modulus')
    num1 = int(input('Enter first number:'))
    num2 = int(input('Enter second number:'))
    print(f'Modulus of {num1} and {num2} is {num1 % num2}')
elif operation == '6':
    print('You have selected Exponent')
    num1 = int(input('Enter first number:'))
    num2 = int(input('Enter second number:'))
    print(f'Exponent of {num1} and {num2} is {num1 ** num2}')
elif operation == '7':
    print('You have selected Floor Division')
    num1 = int(input('Enter first number:'))
    num2 = int(input('Enter second number:'))
    print(f'Floor Division of {num1} and {num2} is {num1 // num2}')
elif operation == '8':
    print('You have selected Exit')
    print('Thank you for using Basic Python Calculator')
else:
    print('Invalid Input')
    print('Please select the operation you want to perform')
    print('1. Addition')
    print('2. Subtraction')
    print('3. Multiplication')
    print('4. Division')
    print('5. Modulus')
    print('6. Exponent')
    print('7. Floor Division')
    print('8. Exit')
    operation = input('Enter your choice (1/2/3/4/5/6/7/8):')
    
    